# Develop override settings

# =====================
# Site Settings
# =====================
baseurl                  : "/niehaitao"

analytics:
  provider: false

comments:
  disqus:
    shortname            : "mmistakes-dev"

sass:
  style: expanded