remote_theme: mmistakes/so-simple-theme
# pmarsceill/just-the-docs


title: "Simply-Re-Explained topics on DEV & OPS"
description: "by Haitao NIE\nJava Software Engineer for a decade then SRE since 2020"
url: "https://niehaitao.github.io"

read_time: true
words_per_minute: 200

category_archive_path: "/categories/#"
tag_archive_path: "/tags/#"