remote_theme: mmistakes/so-simple-theme

url: "https://niehaitao.github.io"

read_time: true
words_per_minute: # 200

# Build settings
permalink: /:categories/:title/


# Pagination - https://jekyllrb.com/docs/pagination/
paginate: 10
paginate_path: /page:num/

# Search
search_full_content: false

# Taxonomy pages
category_archive_path: "/categories/#"
tag_archive_path: "/tags/#"

# Collections
collections:
  dev:
    output: true
    permalink: /:collection/:path/
  ops:
    output: true
    permalink: /:collection/:path/
# Front Matter Defaults
defaults:
  # Post defaults
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      comments: true
      share: true
  - scope:
      path: "_dev"
      type: dev
    values:
      layout: post
      comments: true
      share: true
  - scope:
      path: "_ops"
      type: ops
    values:
      layout: post
      comments: true
      share: true
