remote_theme: mmistakes/so-simple-theme

url: "https://niehaitao.github.io"

title: "TL;DR for DEV and OPS"
description: "Simply Re-Explained by Haitao NIE"

read_time: true
words_per_minute: # 200

# Build settings
permalink: /:categories/:title/

# Search
search_full_content: false

# Taxonomy pages
category_archive_path: "/categories/#"
tag_archive_path: "/tags/#"

# Front Matter Defaults
defaults:
  # Post defaults
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      comments: true
      share: true
