version: "3.7"
services:
  db:
    container_name: act-db
    image: postgres:9.6.21-alpine
    environment:
      POSTGRES_USER: foo
      POSTGRES_PASSWORD: bar
      POSTGRES_DB: demo
    volumes:
      - ./init-db.sql:/docker-entrypoint-initdb.d/init.sql

  api:
    container_name: api
    image: ghcr.io/pop-cloud/activities-api:0.0.1
    ports:
      - 8081:8080
    depends_on:
      - db
    environment:
      db_host: act-db
      db_port: 5432
      db_user: foo
      db_pass: bar
      db_name: demo

  web:
    container_name: web
    image: ghcr.io/pop-cloud/activities-web:0.0.1
    ports:
      - 8082:80