version: "3.7"
services:
  db:
    container_name: act-db
    image: postgres:9.6.21-alpine
    environment:
      POSTGRES_USER: foo
      POSTGRES_PASSWORD: bar
      POSTGRES_DB: demo
    volumes:
      - ./init-db.sql:/docker-entrypoint-initdb.d/init.sql

  api:
    build: ./api
    container_name: api
    ports:
      - 8081:8080
    depends_on:
      - db
    environment:
      db_host: act-db
      db_port: 5432
      db_user: foo
      db_pass: bar
      db_name: demo

  web:
    build:
      context: ./web
      dockerfile: ops/docker/app.dockerfile
      args:
        ENV: test
        GIT_HASH: 1234
        BUILD: '2021-11-10 15:30:00'
    container_name: web
    ports:
      - 8082:80